---
title: "Course Syllabus"
format: html
toc: true
sidebar: false
editor: source
---

## Course Description

In the United States, overall life expectancy has increased dramatically from 69.8 years in 1960 to 78.4 years in 2023 per the Centers for Disease Control and Prevention. While this represents an increase of over 12 percent, it lags behind the gains seen in other developed nations (e.g., the United Kingdom). Although these estimates are moderated by sex, race, and ethnicity within the U.S. with lower life expectancy for males and individuals of American Indian and Alaska Native or Black single race groups, the trend toward greater longevity is clear. This independent study course explores the implications of an aging population for local governments and planning practice across the United States. It integrates demographic, economic, social, and urban development indicators with best practices and innovative initiatives to better understand the challenges and opportunities the “silver tsunami” presents for cities, towns, and rural areas.

This independent study course was developed as a collaboration between students and faculty at the University of Illinois at Urbana-Champaign and the University of Virginia. Enrolled students at both institutions will follow a common meeting schedule, complete the same assigned readings, and submit complementary assignments. Although the course is primarily asynchronous, participants at the two institutions will convene via Zoom twice during the semester to exchange ideas and to chart next steps. Specific goals of the course include:

-   Exploring the intersections of aging, public health, and planning with a focus on how the built environment affects the lives of older adults;
-   Reflecting on historical and contemporary examples of ageism in planning;
-   Evaluating global and local age-friendly initiatives and how they engage with planning;
-   Documenting the network of organizations that serve older people in Champaign-Urbana and Charlottesville;
-   Considering how inclusive design and public policy can promote and enhance health equity for aging populations;
-   Communicating the importance of inclusive public spaces and their role in promoting health equity for aging populations

### Expected Student Learning Outcomes/Objectives:

This independent study course will facilitate student exploration of emerging planning issues related to increasing overall longevity and its implications for communities of all sizes. It is structured as a collaborative research venture with the aim of producing materials and insights that will be useful outside and beyond the classroom. Guiding questions for the course include:

1.  What does the network of organizations that provide services for older people in Champaign-Urbana and Charlottesville look like? How are the participating organizations linked? Do they complement one another?

2.  Are local governments in Champaign-Urbana and Charlottesville proactively planning for an aging population? If so, which domains of planning are engaged the most and the least?

3.  What barriers exist to mainstreaming age-friendly planning and design practices? Are there examples of communities across and outside of the United States successfully overcoming those barriers that can be replicated in or adapted to Champaign-Urbana and Charlottesville?

4.  How can urban planning practices be adapted to better accommodate the needs of an aging population, ensuring accessibility, safety, and quality of life in cities, towns, and rural areas?

### Tasks and Assignments:

In addition to a targeted literature review, enrolled students will conduct primary and secondary research to respond to the guiding questions identified above. The primary focus for each group of students will be the university towns in which they live—Champaign-Urbana, Illinois and Charlottesville-Albemarle, Virginia—but these will be contrasted with either one larger city (e.g., Chicago, Baltimore) or one rural community (e.g., Paris, Lovingston). Although students will jointly design the comparative framework and research method, potential work products include:

-   Targeted literature review to identify gaps in existing planning research related to the guiding questions

-   Brief case studies of communities elsewhere in the United States and abroad that offer important lessons on successfully planning for an aging population

-   Qualitative content analysis of publicly available planning documents

-   Organization map that documents and visualizes existing institutional infrastructure and services for older adults

-   Key informant interviews with urban planners and organizations serving older people within the Champaign-Urbana, Illinois and Charlottesville-Albemarle, Virginia regions

-   Understand what the local/regional needs are and ways to bridge gaps that exist

-   Report and/or Story Map comparing communities at different places along the urban-rural continuum o Demographic trends, housing stock, economic base/industry mix, state and local policy landscape (e.g., support for elderly residents) as context

-   Evaluation of whether and how planning is engaging these issues and resident groups

-   Recommendations that draw upon best practices and case studies

-   A final presentation that synthesizes and shares what has been learned

### Grading:

| Final Grade | Total |
|-------------|-------|
| A+          | 100   |
| A           | 95-99 |
| A-          | 90-94 |
| B+          | 87-89 |
| B           | 83-86 |
| B-          | 80-82 |
| C+          | 77-79 |
| C           | 73-76 |
| C-          | 70-72 |
| D+          | 67-69 |
| D           | 63-66 |
| D-          | 60-62 |
| F           | 0-59  |

: Grading Scheme

| Assignment         | Contribution | Due Date       | Type             |
|--------------------|--------------|----------------|------------------|
| Literature Review  | 15%          | September 26th | All Students     |
| Deep Dive Summary  | 20%          | October 9th    | University Teams |
| Interview Protocol | 5%           | October 16th   | All Students     |
| Interviews Summary | 15%          | November 6th   | University Teams |
| Final Presentation | 15%          | December 4th   | University Teams |
| Report / Story Map | 30%          | December 16th  | University Teams |

: Assignments

Your grade will reflect the quality of your work and fulfillment of the expectations outlined in this syllabus. A general description of the instructor’s expectations for each letter grade is given below:

**‘A’ Excellent work:** Work reflects outstanding achievement in both content and execution. Work must far surpass the given requirements.

**‘B’ Good work:** Work reflects high achievement in both content and execution and must excel beyond the given requirements.

**‘C’ Inadequate work:** Work does not fulfill the given requirements.

**‘D’ Poor work:** Work is less than satisfactory and does not fulfill requirements.

**‘F’ Failing Work:** Work fulfills few, if any, of the requirements.

**‘I’ Incomplete work:** Grade is only available due to health reasons or other emergency situations.

### Accommodations for Religious Observances

For those students who need to miss class due to a religious observance, please complete the [Request for Accommodation for Religious Observances](https://odos.illinois.edu/community-of-care/resources/students/religious-observances/) form should any instructors require an absence letter in order to manage the absence. In order to best facilitate planning and communication between students and faculty, we request that students make requests for absence letters as early as possible in the semester in which the request applies.

For more information on attendance policy as described in the University of Illinois Student Code, please see Sections [1-501](https://studentcode.illinois.edu/article1/part5/1-501/) and [1-502](https://studentcode.illinois.edu/article1/part5/1-502/).

### Accommodations for Students with Disabilities

If you need accommodations for any sort of disability, please make an office hours appointment so we can discuss your needs and ways I can support your learning. To ensure that disability-related concerns are properly addressed, students who require assistance to participate in this class should contact [Disability Resources and Educational Services (DRES)](https://www.disability.illinois.edu). DRES provides students with academic accommodations, access, and support services. To contact DRES you may visit 1207 S. Oak St., Champaign, call 333-4603 (V/TDD), or e-mail [disability\@illinois.edu](mailto:%20disability@illinois.edu).

## Honor Code and Learning Environment

The Illinois Student Code states: "It is the responsibility of each student to refrain from infractions of academic integrity, from conduct that may lead to suspicion of such infractions, and from conduct that aids others in such infractions." Note that you are subject to the Honor Code, as well as procedures for addressing violations to the Code, regardless of whether you have read it and understand it. According to the Code, "ignorance is no excuse."

To meet this standard in this class, note the following: in written work, all ideas (as well as data or other information) that are not your own must be cited. Note that ideas that require citation may not have been published or written down anywhere. While you are free---and indeed encouraged---to discuss the assignments with your peers, all of your data collection, analysis, and writing should be your own. Sharing of data sources you have been assigned to collect is a violation of the honor code in this course. The penalty for failing to meet the principles or spirit of the honor code may include automatic failure of the assignment or the class, at the discretion of the instructor.

The Department of Urban and Regional Planning is committed to maintaining a learning environment that is rooted in the goals and responsibilities of professional planners. By enrolling in a class offered by the Department of Urban and Regional Planning, students agree to be responsible for maintaining an atmosphere of mutual respect in all activities, including lectures, discussions, labs, projects, and extracurricular programs. See Student Code Article 1-Student Rights and Responsibilities, Part 1. Student Rights: §1-102.

### Health and Safety

Following University policy, all students are required to engage in appropriate behavior to protect the health and safety of the community. If you feel ill, do not come to class. In addition, if you test positive for COVID-19 or have had an exposure that requires testing and/or quarantine, do not attend class. Please notify me, and at my discretion, you will be given excused absences for these class sessions. We will also develop a plan to discuss how to make up any missed work.

### Staying in Touch

As you learn and face challenges this semester, I need you to communicate with me, either during our course sessions or individually. You can schedule an appointment with me at your convenience via my [Calendly page]({{< var instructor.calendly_url >}}). I promise to listen, to be a resource, and to help in any way that I can - if I can't help you, I will find someone who can.

### Sexual Misconduct Reporting Obligation

The University of Illinois is committed to combating sexual misconduct. Faculty and staff members are required to report any instances of sexual misconduct to the University's Title IX and Disability Office. In turn, an individual with the Title IX and Disability Office will provide information about rights and options, including accommodations, support services, the campus disciplinary process, and law enforcement options.

A list of the designated University employees who, as counselors, confidential advisors, and medical professionals, do not have this reporting responsibility and can maintain confidentiality, can be found [here](wecare.illinois.edu/resources/students/#confidential). Other information about resources and reporting is available at [wecare.illinois.edu](wecare.illinois.edu).

### Mental Health

The University of Illinois offers a variety of confidential services including individual and group counseling, crisis intervention, psychiatric services, and specialized screenings which are covered through the Student Health Fee. If you or someone you know experiences mental health concerns, please contact or visit any of the University's resources provided below. Getting help is a smart and courageous thing to do for yourself and for those who care about you.

-   [Counseling Center](https://counselingcenter.illinois.edu/): (217) 333-3704
-   [McKinley Health Center](https://mckinley.illinois.edu): (217) 333-2700
-   [988 Suicide and Crisis Lifeline](https://988lifeline.org/?utm_source=google&utm_medium=web&utm_campaign=onebox): (800) 273-8255
-   [Rosecrance Crisis Line](https://rosecrance.org/central-illinois/) (217) 359-4141

If you are in immediate danger, call 911.
