---
title: "Reading List"
format: html
toc: true
editor: source
---

## Big Picture

Forsyth, A., & Molinsky, J. (2021). What is aging in place? Confusions and contradictions. Housing Policy Debate, 31(2), 181-196.

Interagency Coordinating Committee on Healthy Aging and Age-Friendly Communities (2024). Aging in the United States: A Strategic Framework for a National Plan on Aging. ([PDF](https://acl.gov/sites/default/files/ICC-Aging/StrategicFramework-NationalPlanOnAging-2024.pdf))

Kaufman, J. (1961). Planning and an Aging Population. American Society of Planning Officials. ([Link](https://www.planning.org/pas/reports/report148.htm))

Katz, I., & Kaplan, M. (2022). Intergenerational Community Planning, PAS Report 603. Chicago, IL: American Planning Association. ([PDF](https://planning-org-uploaded-media.s3.amazonaws.com/publication/download_pdf/PAS-Report-603.pdf))

Mather, M., & Scommegna, P. (2024). “Fact Sheet: Aging in the United States.” Washington, DC: Population Reference Bureau. ([Link](https://www.prb.org/resources/fact-sheet-aging-in-the-united-states))

New York Times Editorial Board. (2023). “Can America Age Gracefully?” ([Link](https://www.nytimes.com/interactive/2023/09/06/opinion/seniors-old-age-america.html))

World Health Organization. (2023). National programmes for age-friendly cities and communities: A guide. ([PDF](https://iris.who.int/bitstream/handle/10665/366634/9789240068698-eng.pdf))


## Case Studies

American Association of Retired Persons. (2025). “AARP Livable Communities Map.” ([Link](https://livablemap.aarp.org/#/view=map/f7=1,2,3))

Perez-Amado, V., Biglieri, S., Mani, V., & Vijayakumar, R. (2025). Ageing together: a policy case study analysis of socio-spatial inequities for older adults. Journal of Urban Design, 30(2), 179-202. 

Rémillard-Boilard, S., Buffel, T., & Phillipson, C. (2021). Developing age-friendly cities and communities: Eleven case studies from around the world. International Journal of Environmental Research and Public Health, 18(1), 133.

World Health Organization. (2018). The Global Network for Age-friendly Cities and Communities. ([PDF](https://iris.who.int/bitstream/handle/10665/278979/WHO-FWC-ALC-18.4-eng.pdf))
 

## Economic Factors

Myers, D., & Ryu, S. (2008). Aging Baby Boomers and the Generational Housing Bubble: Foresight and Mitigation of an Epic Transition. Journal of the American Planning Association, 74(1), 17-33.

National Academies of Sciences, Engineering, and Medicine. (2022). Understanding the Aging Workforce: Defining a Research Agenda. Washington, DC: The National Academies Press. ([Link](https://doi.org/10.17226/26173))


## Ethics

Lewis, J. (2022). Older Adults: The detached ageism of the planning profession. In Dorina Pojani (Ed.), Alternative Planning History and Theory (pp. 79-93). Routledge.

Mah, J. (2023). Broadening equitable planning: Understanding indirect displacement through seniors’ experiences in a resurgent Downtown Detroit. Environment and Planning A: Economy and Space, 55(4), 905-922.


## Health Factors

Dogra, S., Dunstan, D. W., Sugiyama, T., Stathi, A., Gardiner, P. A., & Owen, N. (2022). Active aging and public health: evidence, implications, and opportunities. Annual Review of Public Health, 43(1), 439-459.

Brookings Institute Center on Health Policy. (2024) The Mental Health Landscape for Older Adults in the US. ([PDF](https://www.brookings.edu/wp-content/uploads/2024/06/20240702_CHP_Frank_OlderAdultsMH.pdf))

Office of Disease Prevention and Health Promotion. (2025) Social Determinants of Health and Older Adults. ([Link](https://odphp.health.gov/our-work/national-health-initiatives/healthy-aging/social-determinants-health-and-older-adults))


## Social Factors

Culhane, D., Treglia, D., Byrne T., Metraux, S., Kuhn, R., Doran, K., Johns, E., & Schretzman, M. (2019). The Emerging Crisis of Aged Homelessness. ([Link](https://aisp.upenn.edu/aginghomelessness/))

Hong, A., Welch-Stockton, J., Kim, J. Y., Canham, S. L., Greer, V., & Sorweid, M. (2023). Age-friendly community interventions for health and social outcomes: A scoping review. International Journal of Environmental Research and Public Health, 20(3), 2554.

McKiernan, D. (2025). License to Thrive in an Aging America: Addressing Transportation Barriers to Social Connectedness for Older Adults in North Carolina. Master’s Thesis, UNC-Chapel Hill. ([Link](https://cdr.lib.unc.edu/concern/masters_papers/1g05fs21f))


## Urban Development

Ali, M. J., Rahaman, M., & Hossain, S. I. (2022). Urban green spaces for elderly human health: A planning model for healthy city living. Land Use Policy, 114, 105970. 

American Planning Association. Aging in Place: Planning’s Role and Responsibilities. ([Link](https://www.planning.org/podcast/aging-in-place-plannings-role-and-responsibilities/))

Davis, S., Clark, A., & Vespa, J. (2023). Aging-Ready Homes in the United States—Perception Versus Reality of Aging-Accessibility Needs: 2019. Washington, DC: U.S. Census Bureau, Current Population Reports. ([PDF](https://www.census.gov/content/dam/Census/library/publications/2023/demo/p23-219.pdf))

Pineo, H. (2022). Towards healthy urbanism: inclusive, equitable and sustainable (THRIVES)–an urban design and planning framework from theory to praxis. Cities & Health, 6(5), 974-992. 

Salmistu, S., & Kotval, Z. (2023). Spatial interventions and built environment features in developing age-friendly communities from the perspective of urban planning and design. Cities, 141, 104417.

Sequeira, R. (2023). “Older adults want to ‘age in place,’ but their options are limited in most states.” Stateline, 2 November. ([Link](https://stateline.org/2023/11/02/older-adults-want-to-age-in-place-but-their-options-are-limited-in-most-states))

Wang, C., Sierra Huertas, D., Rowe, J. W., Finkelstein, R., Carstensen, L. L., & Jackson, R. B. (2021). Rethinking the urban physical environment for century-long lives: From age-friendly to longevity-ready cities. Nature Aging, 1(12), 1088-1095. 

Warner, M. E., & Zhang, X. (2022). Planning communities for all ages. Journal of Planning Education and Research, 42(4), 554-567.



